name: Deploy to GitHub Pages

#Run workflow every push to main.
on:
  push:
    branches: [main]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    #Set up .NET Core SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    #Publish project to the release-folder
    -name: Publish .NET Core Project
    run: dotnet publish blazor-github-pages.csproj -c Release -o release --nologo
    
    -name: commit wwroot to GitHub Pages
    uses: JamesIves/github-pages-deploy-action@3.7.1
    with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: main
        FOLDER: release/wwwroot
